os: Visual Studio 2015
platform: x64
build: script

environment:
  PYTHON: "C:\\Python36-x64"

install:
  - ps: Start-FileDownload 'https://download.microsoft.com/download/2/9/e/29efe9b1-16d7-4912-a229-6734b0c4e235/msmpisdk.msi'
  - ps: Start-FileDownload 'https://download.microsoft.com/download/2/9/e/29efe9b1-16d7-4912-a229-6734b0c4e235/MSMpiSetup.exe'
  - msmpisdk.msi /passive
  - MSMpiSetup.exe -unattend
  - set PATH=%PYTHON%;%PYTHON%\Scripts;C:\Program Files\Microsoft MPI\Bin;%PATH%

build_script:
  - python setup.py test

