os: Visual Studio 2015
platform: x64
build: script

environment:
  MINICONDA_ROOT: C:\Miniconda36-x64

install:
  - call "%MINICONDA_ROOT%\Scripts\activate.bat" root
  - conda install -y -q pip setuptools

build_script:
  - python setup.py test

